/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as PracownicyRouteImport } from './routes/pracownicy'
import { Route as OpinieRouteImport } from './routes/opinie'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UslugiKosmetologiaRouteImport } from './routes/uslugi.kosmetologia'

const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const PracownicyRoute = PracownicyRouteImport.update({
  id: '/pracownicy',
  path: '/pracownicy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinieRoute = OpinieRouteImport.update({
  id: '/opinie',
  path: '/opinie',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiKosmetologiaRoute = UslugiKosmetologiaRouteImport.update({
  id: '/kosmetologia',
  path: '/kosmetologia',
  getParentRoute: () => UslugiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/opinie': typeof OpinieRoute
  '/pracownicy': typeof PracownicyRoute
  '/regulamin': typeof RegulaminRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/kosmetologia': typeof UslugiKosmetologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/opinie': typeof OpinieRoute
  '/pracownicy': typeof PracownicyRoute
  '/regulamin': typeof RegulaminRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/kosmetologia': typeof UslugiKosmetologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/opinie': typeof OpinieRoute
  '/pracownicy': typeof PracownicyRoute
  '/regulamin': typeof RegulaminRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/kosmetologia': typeof UslugiKosmetologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cennik'
    | '/opinie'
    | '/pracownicy'
    | '/regulamin'
    | '/uslugi'
    | '/uslugi/kosmetologia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik'
    | '/opinie'
    | '/pracownicy'
    | '/regulamin'
    | '/uslugi'
    | '/uslugi/kosmetologia'
  id:
    | '__root__'
    | '/'
    | '/cennik'
    | '/opinie'
    | '/pracownicy'
    | '/regulamin'
    | '/uslugi'
    | '/uslugi/kosmetologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CennikRoute: typeof CennikRoute
  OpinieRoute: typeof OpinieRoute
  PracownicyRoute: typeof PracownicyRoute
  RegulaminRoute: typeof RegulaminRoute
  UslugiRoute: typeof UslugiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pracownicy': {
      id: '/pracownicy'
      path: '/pracownicy'
      fullPath: '/pracownicy'
      preLoaderRoute: typeof PracownicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinie': {
      id: '/opinie'
      path: '/opinie'
      fullPath: '/opinie'
      preLoaderRoute: typeof OpinieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/kosmetologia': {
      id: '/uslugi/kosmetologia'
      path: '/kosmetologia'
      fullPath: '/uslugi/kosmetologia'
      preLoaderRoute: typeof UslugiKosmetologiaRouteImport
      parentRoute: typeof UslugiRoute
    }
  }
}

interface UslugiRouteChildren {
  UslugiKosmetologiaRoute: typeof UslugiKosmetologiaRoute
}

const UslugiRouteChildren: UslugiRouteChildren = {
  UslugiKosmetologiaRoute: UslugiKosmetologiaRoute,
}

const UslugiRouteWithChildren =
  UslugiRoute._addFileChildren(UslugiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CennikRoute: CennikRoute,
  OpinieRoute: OpinieRoute,
  PracownicyRoute: PracownicyRoute,
  RegulaminRoute: RegulaminRoute,
  UslugiRoute: UslugiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
